apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-mundo
  namespace: default
  labels:
    app: hola-mundo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hola-mundo
  template:
    metadata:
      labels:
        app: hola-mundo
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
