apiVersion: v1
kind: Service
metadata:
  name: hola-mundo
  namespace: default
  labels:
    app: hola-mundo
spec:
  selector:
    app: hola-mundo
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
